apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: monitoring
spec:
  selector:
    app: pushgateway
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  type: ClusterIP # You can change this to LoadBalancer or NodePort if needed
