apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: resource monitoring
      rules:
      - alert: HostOutOfDiskSpace
        expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 20
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "Host out of disk space (instance {{ $labels.instance }})"
          descriptions: "Disk is almost full (< 20% left)\n VALUE = {{ $value }}\n LABELS = {{ $labels }}"


      - alert: Prometeues Target is Down
        expr: up == 0
        for: 0m
        labels:
          severity: Disaster
        annotations:
          summary: "Target (instance {{ $labels.instance }}) is Down"
          descriptions: "Latest Value  VALUE = {{ $value }}\n LABELS = {{ $labels }}"



      - alert: Disk Alert
        expr: (node_filesystem_avail_bytes{mountpoint="/"} <= bool 90729014784) == 1
        for: 0m
        labels:
          severity: Disaster
        annotations:
          summary: "Target (instance {{ $labels.instance }}) is Down"
          descriptions: "Latest Value  VALUE = {{ $value }}\n LABELS = {{ $labels }}"


  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"

    scrape_configs:
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'node-exporter'
          action: keep



      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

      - job_name: 'dev-push-gateway'
        metrics_path: /metrics
        scheme: http
        static_configs:
         - targets: ['10.104.185.219:9091']
           labels:
            service: 'prom-pushgateway'
